- project:
    templates:
      - openstack-specs-jobs
    check:
      jobs:
        - service-types-authority-tox-publish
        - openstack-tox-pep8
    gate:
      jobs:
        - service-types-authority-tox-publish
        - openstack-tox-pep8
    promote:
      jobs:
        - promote-service-types-authority

- job:
    name: service-types-authority-tox-publish
    parent: opendev-tox-docs
    description: |
      Publishes files of service-types-authority project.

      Uses tox with the ``publish`` environment.
    vars:
      tox_envlist: publish
